package tools

import gorm "gorm.io/gorm"

//Generated By github.com/davidyap2002/GormCrudGenerator

//QueryMaker Pagination Query Tools
func QueryMaker(query *gorm.DB, limit int, page int, ascending bool, sortBy string, filter []int) {
	offset := (page - 1) * limit
	sortBy = OrderBy(sortBy, ascending)

	StatusFilter(query, filter)

	if limit > 0 && page > 0 {
		*query = *query.Offset(offset).Limit(limit)
	}

	*query = *query.Order(sortBy)
}

//OrderBy Order By Generator (ASC,DESC)
func OrderBy(sortBy string, ascending bool) string {
	if ascending {
		return sortBy + " ASC"
	}
	return sortBy + " DESC"
}

//StatusFilter Filtering By Status
func StatusFilter(query *gorm.DB, filter []int) {
	filterLen := len(filter)

	if filterLen > 0 {
		*query = *query.Where("status IN (?)", filter)
	}
}
