package tools

//Generated By github.com/davidyap2002/GormCrudGenerator

//PaginationVariableGenerator Pagination Variable Generator Tools
func PaginationVariableGenerator(limiter *int, numberPage *int, ascending *bool, sortBy *string, filter []*int) (int, int, bool, string, []int) {
	var limit int
	var page int
	var asc bool
	var sort string
	var status []int

	if limiter != nil {
		limit = *limiter
	} else {
		limit = 0
	}

	if numberPage != nil {
		page = *numberPage
	} else {
		page = 0
	}

	if ascending != nil {
		asc = *ascending
	} else {
		asc = true
	}

	if sortBy != nil {
		sort = *sortBy
	} else {
		sort = "id"
	}

	if filter != nil {
		for _, val := range filter {
			status = append(status, *val)
		}
	} else {
		status = []int{}
	}
	return limit, page, asc, sort, status
}
